#!/bin/bash

# -----------------------------------------------------
# Hardware Acceleration - Vulkan
# -----------------------------------------------------

# Function to set the MESA_VK_DEVICE_SELECT variable dynamically (https://wiki.archlinux.org/title/Vulkan#Switching_between_devices)
set_mesa_vk_device() {

    unset MESA_VK_DEVICE_SELECT

    # Make sure vulkaninfo is installed
    if ! command -v vulkaninfo &>/dev/null; then
        echo "vulkaninfo not found. Did you install it?"
        return 1
    fi

    local vk_devices nvidia_id amd_id intel_id

    # Get available devices
    vk_devices=$(LC_ALL=C MESA_VK_DEVICE_SELECT=list vulkaninfo 2>&1)

    # Print an error if none are found
    if [[ -z "$vk_devices" ]]; then
        echo "Failed to list Vulkan devices."
        return 1
    fi

    # Extract vendorID:deviceID from the output of vulkaninfo
    nvidia_id=$(grep -Eo "10de:[0-9a-f]{4}" <<< "$vk_devices" | head -n1)
    amd_id=$(grep -Eo "1002:[0-9a-f]{4}" <<< "$vk_devices" | head -n1)
    intel_id=$(grep -Eo "8086:[0-9a-f]{4}" <<< "$vk_devices" | head -n1)

    # Set the GPU used for Vulkan
    if [[ -n "$nvidia_id" ]]; then
        export MESA_VK_DEVICE_SELECT="$nvidia_id"
        echo "MESA_VK_DEVICE_SELECT set to $MESA_VK_DEVICE_SELECT (NVIDIA)"
    elif [[ -n "$amd_id" ]]; then
        export MESA_VK_DEVICE_SELECT="$amd_id"
        echo "MESA_VK_DEVICE_SELECT set to $MESA_VK_DEVICE_SELECT (AMD)"
    elif [[ -n "$intel_id" ]]; then
        export MESA_VK_DEVICE_SELECT="$intel_id"
        echo "MESA_VK_DEVICE_SELECT set to $MESA_VK_DEVICE_SELECT (Intel)"
    else
        echo "No supported Vulkan devices found."
    fi
}
set_mesa_vk_device





# -----------------------------------------------------
# Hardware Video Acceleration - VA-API
# -----------------------------------------------------

# Function to set the LIBVA_DRIVER_NAME variable dynamically (https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VA-API)
# If the libva-nvidia-driver package isn't installed, the Nvidia dGPU can't be used for VA-API. Install it with: sudo pacman -S --needed libva-nvidia-driver
set_vaapi_driver() {

    # This function relies on set_mesa_vk_device, as to not conflict with vfio-pci configuration,
    # see https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Binding_vfio-pci_via_device_ID

    unset LIBVA_DRIVER_NAME

    case "$MESA_VK_DEVICE_SELECT" in
        10de:*)  # NVIDIA
            export LIBVA_DRIVER_NAME=nvidia
            echo "LIBVA_DRIVER_NAME set to nvidia"
            ;;
        1002:*)  # AMD
            export LIBVA_DRIVER_NAME=radeonsi
            echo "LIBVA_DRIVER_NAME set to radeonsi (AMD)"
            ;;
        8086:*)  # Intel
            export LIBVA_DRIVER_NAME=iHD
            echo "LIBVA_DRIVER_NAME set to iHD (Intel)"
            ;;
        *)
            echo "Unknown or unset MESA_VK_DEVICE_SELECT. LIBVA_DRIVER_NAME not set."
            ;;
    esac
}
set_vaapi_driver





# -----------------------------------------------------
# Hardware Video Acceleration - VDPAU
# -----------------------------------------------------

# Function to set the VDPAU_DRIVER variable dynamically (https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VDPAU)
# This requires the libvdpau-va-gl package to be installed (sudo pacman -S --needed libvdpau-va-gl). Otherwise, the Intel iGPU can't be used for VDPAU

set_vdpau_driver() {

    # This function relies on set_mesa_vk_device, as to not conflict with vfio-pci configuration,
    # see https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Binding_vfio-pci_via_device_ID

    unset VDPAU_DRIVER

    case "$MESA_VK_DEVICE_SELECT" in
        10de:*)  # NVIDIA
            export VDPAU_DRIVER=nvidia
            echo "VDPAU_DRIVER set to nvidia"
            ;;
        1002:*)  # AMD
            export VDPAU_DRIVER=radeonsi
            echo "VDPAU_DRIVER set to radeonsi (AMD)"
            ;;
        8086:*)  # Intel
            export VDPAU_DRIVER=va_gl
            echo "VDPAU_DRIVER set to va_gl (Intel)"
            ;;
        *)
            echo "Unknown or unset MESA_VK_DEVICE_SELECT. VDPAU_DRIVER not set."
            ;;
    esac
}
set_vdpau_driver
