# Extra settings can be found here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# And here: https://alacritty.org/config-alacritty.html

####################################################################

[cursor]
blink_interval = 500 # Milliseconds
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Always"

####################################################################

# Make sure the font you want to use is installed. If not, search for it and use pacman to install it
# Example with JetBrains Mono Nerd Font: sudo pacman -S --needed ttf-jetbrains-mono-nerd
[font]
size = 10.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

####################################################################

# Select a color theme
# Here's a good repository: https://github.com/alacritty/alacritty-theme
[general]
import = [ "~/.config/alacritty/themes/xterm.toml" ]

####################################################################

[scrolling]
history = 5000

####################################################################

[terminal.shell]
program = "/usr/bin/bash"

####################################################################

[window]
##opacity = 1
opacity = 0.7

#padding.x = 10
#padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # Accepts "Light", "Dark" or "None" (which uses the system configuration)

dynamic_title = true

[window.dimensions]
lines = 52
columns = 160
